# Generated by Django 3.2.8 on 2022-01-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_remove_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(default=0, max_length=100, verbose_name='Categoría'),
            preserve_default=False,
        ),
    ]
